# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'News' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'SDWebImage', :modular_headers => true
    pod 'SVProgressHUD'
    pod 'KSBGradientView'
    pod 'SwiftSoup'
    pod 'Charts'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
  # Pods for News

end
